server
{
    listen 1;
    error_page 404 error/error404;
    error_page 405 error/error405; 
    client_max_body_size 40000;
    location .
    {
        root .;
        autoindex on;
        methods GET POST DELETE;
        return 1 error/return;
        upload_store upload;
        index index1;
        cgi_extension .php cgi/php;
        cgi_extension .py cgi/py;
    }
}
server
{
    listen 1;
    error_page 404 error/error404;
    error_page 405 error/error405; 
    client_max_body_size 40000;
    location .
    {
        root .;
        autoindex on;
        methods GET POST DELETE;
        return 1 error/return;
        upload_store upload;
        index index1;
        cgi_extension .php cgi/php;
        cgi_extension .py cgi/py;
    }
}
