server
{
    listen 8094;
    error_page 301 errors/301.html;
    error_page 403 errors/403.html;
    error_page 404 errors/404.html;
    error_page 500 errors/500.html;
    client_max_body_size 40000;


	location /test
    {
		root /var/www/html;
        autoindex on;
        methods GET POST DELETE;
        return 1 errors/return;
        upload_store upload;
        index index1;
        cgi_extension .php cgi/php;
        cgi_extension .py cgi/py;
    }
}
