server
{
    listen 8096;
    client_max_body_size 6000000;

	location /cgi
    {
		root . ;
        autoindex on;
        return 302 cgi-bin;
        upload_store upload;
        index index1;
        cgi_extension php cgi/php;
        cgi_extension py cgi/py;
    }

	location /cgi-bin
    {
		root . ;
        autoindex on;
        upload_store upload;
        index index1;
        cgi_extension php cgi/php;
        cgi_extension py cgi/py;
    }

	location /uploads
    {
		root . ;
        methods GET POST DELETE;
        autoindex on;
        upload_store ./upload/;
        return 301 upload;
        index index1;
        cgi_extension .php cgi/php;
        cgi_extension .py cgi/py;
    }

	location /upload
    {
		root . ;
        methods GET POST DELETE;
        autoindex on;
        upload_store ./upload/;
        index index1;
        cgi_extension .php cgi/php;
        cgi_extension .py cgi/py;
    }

	location /favicon.ico
    {
		root . ;
        autoindex on;
        upload_store ./upload2/;
        index index1;
        cgi_extension .php cgi/php;
        cgi_extension .py cgi/py;
    }
}
